export function downloadMockCertifiedRecord(record) {
  if (!record) return;

  const issueDate = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric'
  });

  const content = `
================================================================================
 GOVERNMENT OF ODISHA — REVENUE & DISASTER MANAGEMENT DEPARTMENT
 DISTRICT LAND RECORDS CELL — KHORDHA (TEHSIL JATNI)
================================================================================
 PROTOTYPE CERTIFIED COPY OF RECORD OF RIGHTS (PATTA / KHATA EXCERPT)
 ** PROTOTYPE DEMO COPY — NOT AN OFFICIAL LEGAL CERTIFICATE **
================================================================================

DOCUMENT METADATA:
--------------------------------------------------------------------------------
Record ID:          ${record.id}
Document Reference: ${record.documentId}
Issue Date:         ${issueDate}
Mouza / Village:    ${record.village} (Mouza ID: 751024)
Tehsil:             ${record.tehsil}
District:           ${record.district}
State:              ${record.state}

LANDOWNER DETAILS:
--------------------------------------------------------------------------------
Owner Name:         ${record.ownerName}
Father / Husband:   ${record.fatherName || 'N/A'}
Ownership Status:   ${record.verificationStatus === 'VERIFIED' ? 'Certified Rayati Landowner' : 'Provisional Extraction'}

PARCEL & SURVEY SPECIFICATIONS:
--------------------------------------------------------------------------------
Survey Number:      ${record.surveyNumber}
Khata / Khasra No:  Khata No. ${record.khataNumber} | Khasra ${record.khasraNumber || record.surveyNumber}
Plot Area:          ${record.area} ${record.areaUnit}
Classification:     ${record.landClassification}
GIS Parcel Ref:     ${record.parcelGeoJsonRef || 'PARCEL-101'}

VERIFICATION & DIGITIZATION METRICS:
--------------------------------------------------------------------------------
Verification State: ${record.verificationStatus}
AI Confidence:      ${record.overallConfidence}%
Verified By:        ${record.verifiedBy || 'Automated Pipeline Validation'}
Verification Date:  ${record.verifiedAt || 'Pending Certification'}
Digitization Platform: BhuNexis Intelligent Land Record System (SIH 2026)

SECURITY STAMP & QR VERIFICATION:
--------------------------------------------------------------------------------
[ [ SIMULATED DIGITAL SEAL & QR VERIFICATION MATRIX ] ]
Hash Signature: SHA256-${Math.random().toString(36).substr(2, 16).toUpperCase()}-BHUNEXIS
QR Code Payload: https://bhunexis.demo/verify/${record.id}

================================================================================
DISCLAIMER:
This document is generated by the BhuNexis Smart India Hackathon 2026 internal
round frontend demonstration prototype. All names, numbers, boundaries, and
confidence scores are simulated mock data and hold no legal standing in any
court or revenue tribunal.
================================================================================
`;

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `Certified_Land_Record_${record.surveyNumber.replace('/', '_')}_${record.id}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
