import React, { useState, useContext } from 'react';
import { useParams, Link } from 'react-router-dom';
import { AppContext } from '../../context/AppContext';
import { useToast } from '../../hooks/useToast';
import { DashboardLayout } from '../../components/DashboardLayout';
import { StatusBadge } from '../../components/StatusBadge';
import { ConfidenceBar } from '../../components/ConfidenceBar';
import { Modal } from '../../components/Modal';
import { downloadMockCertifiedRecord } from '../../utils/downloadMockRecord';
import { 
  FileText, 
  MapPin, 
  CheckCircle2, 
  Download, 
  AlertCircle, 
  ShieldCheck, 
  QrCode, 
  ArrowLeft,
  Building2,
  FileCheck
} from 'lucide-react';

export function LandRecordDetails() {
  const { id } = useParams();
  const { records, submitGrievance } = useContext(AppContext);
  const { addToast } = useToast();

  const record = records.find(r => r.id === id) || records[0];

  const [isGrievanceModalOpen, setIsGrievanceModalOpen] = useState(false);
  const [grievanceForm, setGrievanceForm] = useState({
    issueType: 'Incorrect Owner Name',
    description: '',
    contactEmail: ''
  });

  if (!record) {
    return (
      <DashboardLayout>
        <div className="text-center py-12 text-slate-500">Record not found.</div>
      </DashboardLayout>
    );
  }

  const handleDownload = () => {
    downloadMockCertifiedRecord(record);
    addToast('Prototype certified copy downloaded in Demo Mode.', 'success');
  };

  const handleGrievanceSubmit = (e) => {
    e.preventDefault();
    submitGrievance({
      recordId: record.id,
      ...grievanceForm
    });
    setIsGrievanceModalOpen(false);
    addToast('Grievance correction request submitted successfully (Demo Mode).', 'success');
  };

  return (
    <DashboardLayout>
      <div className="space-y-6 max-w-4xl mx-auto">
        {/* Navigation Back Link */}
        <Link to="/u/search" className="text-xs font-bold text-sky-600 hover:text-sky-800 flex items-center gap-1 inline-flex">
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Land Record Search</span>
        </Link>

        {/* Main Document Details Card */}
        <div className="bg-white rounded-2xl border border-slate-200 shadow-xl overflow-hidden">
          {/* Header Banner */}
          <div className="bg-gradient-to-r from-slate-900 to-slate-800 text-white p-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div>
              <span className="text-[10px] font-extrabold uppercase tracking-widest text-sky-400 bg-sky-500/10 px-2 py-0.5 rounded border border-sky-500/30">
                Official Record Excerpt
              </span>
              <h1 className="text-2xl font-extrabold tracking-tight mt-1">{record.ownerName}</h1>
              <p className="text-xs text-slate-400 mt-0.5">
                Record ID: <span className="font-mono text-white font-bold">{record.id}</span> • Mouza: {record.village}
              </p>
            </div>

            <StatusBadge status={record.verificationStatus} />
          </div>

          {/* Body Content */}
          <div className="p-6 space-y-6 text-xs text-slate-800">
            {/* Disclaimer Bar */}
            <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl text-amber-900 text-[11px] leading-relaxed flex items-start gap-2">
              <AlertCircle className="w-4 h-4 shrink-0 text-amber-600 mt-0.5" />
              <span>
                <strong>PROTOTYPE CERTIFIED COPY DEMO:</strong> This record view is generated by the BhuNexis Smart India Hackathon 2026 frontend simulation model. Data shown is simulated and does not constitute an official legal certificate.
              </span>
            </div>

            {/* Grid Specifications */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-100">
                <span className="text-slate-400 text-[10px] font-semibold uppercase block">Landowner</span>
                <span className="font-bold text-slate-900 text-sm block">{record.ownerName}</span>
                <span className="text-[11px] text-slate-500">s/o {record.fatherName || 'N/A'}</span>
              </div>

              <div className="p-3 bg-slate-50 rounded-xl border border-slate-100">
                <span className="text-slate-400 text-[10px] font-semibold uppercase block">Survey / Plot No</span>
                <span className="font-bold text-slate-900 text-sm block">{record.surveyNumber}</span>
                <span className="text-[11px] text-slate-500">Khasra: {record.khasraNumber || record.surveyNumber}</span>
              </div>

              <div className="p-3 bg-slate-50 rounded-xl border border-slate-100">
                <span className="text-slate-400 text-[10px] font-semibold uppercase block">Khata Number</span>
                <span className="font-bold text-slate-900 text-sm block">Khata No. {record.khataNumber}</span>
                <span className="text-[11px] text-slate-500">Mouza Patta Registry</span>
              </div>

              <div className="p-3 bg-slate-50 rounded-xl border border-slate-100">
                <span className="text-slate-400 text-[10px] font-semibold uppercase block">Plot Area</span>
                <span className="font-bold text-slate-900 text-sm block">{record.area} {record.areaUnit}</span>
                <span className="text-[11px] text-slate-500">Classification: {record.landClassification}</span>
              </div>

              <div className="p-3 bg-slate-50 rounded-xl border border-slate-100">
                <span className="text-slate-400 text-[10px] font-semibold uppercase block">Administrative Region</span>
                <span className="font-bold text-slate-900 text-sm block">{record.village}</span>
                <span className="text-[11px] text-slate-500">{record.tehsil}, Khordha, {record.state}</span>
              </div>

              <div className="p-3 bg-slate-50 rounded-xl border border-slate-100">
                <span className="text-slate-400 text-[10px] font-semibold uppercase block">Verification Status</span>
                <span className="font-bold text-slate-900 text-sm block">{record.verificationStatus}</span>
                <span className="text-[11px] text-slate-500">Confidence: {record.overallConfidence}%</span>
              </div>
            </div>

            {/* Simulated QR Code & Digital Seal Matrix */}
            <div className="p-4 bg-slate-900 text-white rounded-xl flex flex-col sm:flex-row items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-lg bg-slate-800 border border-slate-700 flex items-center justify-center text-sky-400 shrink-0">
                  <QrCode className="w-7 h-7" />
                </div>
                <div>
                  <h4 className="font-bold text-xs">Simulated Digital Seal & Verification Matrix</h4>
                  <p className="text-[10px] text-slate-400 font-mono">
                    SHA256: {Math.random().toString(36).substr(2, 16).toUpperCase()}-BHUNEXIS
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={handleDownload}
                  className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs rounded-xl shadow-md transition-colors flex items-center gap-1.5"
                >
                  <Download className="w-4 h-4" />
                  <span>Download Certified Copy</span>
                </button>
                <button
                  onClick={() => setIsGrievanceModalOpen(true)}
                  className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 font-semibold text-xs rounded-xl border border-slate-700 transition-colors"
                >
                  Submit Grievance
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Grievance Modal */}
      <Modal
        isOpen={isGrievanceModalOpen}
        onClose={() => setIsGrievanceModalOpen(false)}
        title="Submit Grievance / Correction Request (Demo Mode)"
      >
        <form onSubmit={handleGrievanceSubmit} className="space-y-4 text-xs">
          <div>
            <label className="block font-semibold text-slate-700 mb-1">Select Issue Category</label>
            <select
              value={grievanceForm.issueType}
              onChange={(e) => setGrievanceForm({ ...grievanceForm, issueType: e.target.value })}
              className="w-full bg-slate-50 border border-slate-300 rounded-lg p-2 text-xs font-semibold"
            >
              <option value="Incorrect Owner Name">Incorrect Owner Name Spelling</option>
              <option value="Incorrect Survey Number">Incorrect Survey / Plot Number</option>
              <option value="Incorrect Area">Incorrect Plot Area Measurement</option>
              <option value="Incorrect Village">Incorrect Mouza / Tehsil Classification</option>
              <option value="Other">Other Discrepancy</option>
            </select>
          </div>

          <div>
            <label className="block font-semibold text-slate-700 mb-1">Detailed Description of Discrepancy</label>
            <textarea
              rows={3}
              required
              placeholder="Describe the discrepancy with historical Patta reference..."
              value={grievanceForm.description}
              onChange={(e) => setGrievanceForm({ ...grievanceForm, description: e.target.value })}
              className="w-full bg-slate-50 border border-slate-300 rounded-lg p-2 text-xs"
            />
          </div>

          <div>
            <label className="block font-semibold text-slate-700 mb-1">Contact Email Address</label>
            <input
              type="email"
              required
              placeholder="citizen@bhoomiai.demo"
              value={grievanceForm.contactEmail}
              onChange={(e) => setGrievanceForm({ ...grievanceForm, contactEmail: e.target.value })}
              className="w-full bg-slate-50 border border-slate-300 rounded-lg p-2 text-xs"
            />
          </div>

          <div className="pt-2 flex justify-end gap-2">
            <button
              type="button"
              onClick={() => setIsGrievanceModalOpen(false)}
              className="px-3.5 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-100 rounded-lg"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-4 py-2 text-xs font-bold bg-sky-600 text-white hover:bg-sky-500 rounded-lg shadow-sm"
            >
              Submit Grievance Request
            </button>
          </div>
        </form>
      </Modal>
    </DashboardLayout>
  );
}
